### ISSUE TITLE
Sub-component slot

### ISSUE THREAD

**Issue by kaysersoze** [divijbhardwaj/form-generator-vue#6]
@divijbhardwaj Would there be interest in adding a sub-component slot, to complement the `_before` and `_after` helpers?

One use-case would be something like `v-radio-group` in Vuetify (https://vuetifyjs.com/en/components/radio-buttons/#usage), which can contain `v-radios` inside of it to complete the component.

I've worked around my immediate issue by creating a custom `radio-group` which gets passed the individual radio buttons as label/value pairs, but it might be handy to have the ability to do that in the field schema.

**Comment by divijbhardwaj** [comment]
@kaysersoze Yes you are right, once we do this then this pkg can handle nested components also. I am working on this

**Comment by divijbhardwaj** [comment]
@kaysersoze checkout dev branch, i have added sub component slot there.

**Comment by divijbhardwaj** [comment]
once i release it on npm i will close this issue
